name: FindPlayer
main: dev.ellienntatar.findplayer.FindPlayer
version: 1.14
author: Ellienn Tatar
commands:
   findp:
         description: This command returns a player's coordinates. If a database is specified in the plugin.yml file, this command will return an offline player's last coordinates.
         usage: /findp [player]
         permission: FindPlayer.findp
         permission-message: You don't have access to FindPlayer.findp!
   findplist:
         description: This command returns a list of all players who have joined the server. (a database must have been set up for this command to work.)
         usage: /findplist
         permission: FindPlayer.findplist
         permission-message: You don't have access to FindPlayer.findplist!